version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      PGDATA: ./tools/data/postgres
    volumes:
      - type: bind
        source: ./tools/data/postgres-data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
