logging:
  level:
#    org.springframework.r2dbc: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG
#debug: true
server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?currentSchema=checkout
    username: admin
    password: admin
    properties:
      enableSSL: false
      sslMode: disable
    pool:
      enabled: false

  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0.0
    locations: [ 'classpath:db/migration' ]
    url: jdbc:postgresql://localhost:5432/postgres
    schemas: [ 'checkout' ]
    user: "admin"
    password: "admin"

  output:
    ansi:
      enabled: ALWAYS

  redis:
    url: redis://default:password@localhost:6379
    connect-timeout: 10000
    timeout: 10000
    database: 1

flow:
  redis:
    host: localhost
    port: 6379
    userName: default
    password: password
    ssl: false
    timeout: 5000
    database: 2
    databaseTwo: 1
    databaseThree: -1
  actionLogger:
    enabled: true


application:
  features:
    file: ./tools/features/checkout/features.properties


