server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=poc
    username: admin
    password: admin

  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0.0
    locations: [ 'classpath:db/migration' ]
    url: jdbc:postgresql://localhost:5432/postgres
    schemas: [ 'poc' ]
    user: "admin"
    password: "admin"

  output:
    ansi:
      enabled: ALWAYS

flow:
  actionLogger:
    enabled: true
  taskConsumer:
    scheduleMilli: 1000
  lockService:
    removeBlockedLockScheduleMilli: 10000


